refactor: move build-internal to separate workflow

diff --git a/.github/workflows/image-internal.yaml b/.github/workflows/image-internal.yaml
--- a/.github/workflows/image-internal.yaml
+++ b/.github/workflows/image-internal.yaml
@@ -1,73 +1,78 @@
-name: Build and Publish Rocks
+# This workflow is intended for internal Canonical repositories only. 
+# It includes steps that rely on internal actions or secrets, 
+# and it performs additional checks to prevent accidental usage in public repositories. 
+# If you are working in a public repository, please use the .github/workflows/image.yaml workflow instead.
+#
+name: Build and Publish Rocks (Internal)
 
 on:
-  push:
-    branches: [main]
-  pull_request:
-    branches: [main]
+  # Uncomment these lines to enable the workflow on push and pull_request events
+  # push:
+  #   branches: [main]
+  # pull_request:
+  #   branches: [main]
   workflow_dispatch:
 
 jobs:
 
-  read-config:
+  prepare:
     runs-on: ubuntu-latest
     outputs:
       ghcr-upload: ${{ steps.read-ci-config.outputs.ghcr-upload }}
-      ghcr-cve-scan: ${{ steps.read-ci-config.outputs.ghcr-cve-scan }}
       build-matrix: ${{ steps.read-ci-config.outputs.build-matrix }}
       upload-matrix: ${{ steps.read-ci-config.outputs.upload-matrix }}
     steps:
-      - name: Checkout repository
+      - name: Pre-Check
+        if: |
+          github.repository_owner != 'canonical' ||
+          github.event.repository.visibility == 'public'
+        run: |
+          echo "::error::This workflow is intended for internal repositories only. Please use the .github/workflows/image.yaml workflow instead."
+          exit 1
+
+      - name: Checkout Repository
         uses: actions/checkout@v5
 
       - name: Read .github/ci.yaml
         id: read-ci-config
         uses: canonical/rocks-template-actions/actions/read-ci-config@v1
 
-  get-runners:
-    runs-on: ubuntu-latest
-    outputs:
-      arch-map: ${{ steps.set-map.outputs.arch-map }}
-    steps:
-      - id: set-map
-        run: |
-          if [[ "${{ github.repository_owner }}" == "canonical" ]]; then
-            echo 'arch-map={"amd64":["noble","X64","large"],"arm64":["noble","ARM64","large"]}' >> $GITHUB_OUTPUT
-          else
-            echo 'arch-map={"amd64":["ubuntu-24.04"],"arm64":["ubuntu-24.04-arm"]}' >> $GITHUB_OUTPUT
-          fi
 
-  build:
-    needs: [get-runners, read-config]
+  build-internal:
+    needs: [prepare]
     strategy:
-      matrix: ${{ fromJSON(needs.read-config.outputs.build-matrix) }}
-    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
+      fail-fast: true
+      matrix: ${{ fromJSON(needs.prepare.outputs.build-matrix) }}
+    uses: canonical/oci-factory-internal/.github/workflows/Build-Rock.yaml@main
     with:
-      rock-repo: ${{ github.repository }}
-      rock-repo-commit: ${{ github.head_ref || github.ref_name }}
+      rock-repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
+      rock-repo-commit: ${{ github.ref }}
       rockfile-directory: ${{ matrix.directory }}
       oci-archive-name: ${{ matrix.artifact-name }}
-      arch-map: ${{ needs.get-runners.outputs.arch-map }}
-      rockcraft-test: ${{ matrix.run-tests }}
+    secrets:
+      host-github-token: ${{ secrets.GITHUB_TOKEN }}
+      source-github-token: ${{ secrets.REPO_CLONER_TOKEN }}
+
 
   test:
-    needs: [read-config, build]
+    needs: [prepare, build-internal]
     strategy:
       fail-fast: false
-      matrix: ${{ fromJson(needs.read-config.outputs.build-matrix) }}
+      matrix: ${{ fromJson(needs.prepare.outputs.build-matrix) }}
     uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@main
     with:
       oci-archive-name: ${{ matrix.artifact-name }}
 
+
   upload-ghcr:
-    needs: [read-config, test]
+    needs: [prepare, test]
     runs-on: ubuntu-latest
     if: |
       needs.prepare.outputs.ghcr-upload == 'true' &&
       github.event_name != 'pull_request' && 
       github.ref == 'refs/heads/main'
     strategy:
-      matrix: ${{ fromJSON(needs.read-config.outputs.build-matrix) }}
+      matrix: ${{ fromJSON(needs.prepare.outputs.build-matrix) }}
       fail-fast: false
     permissions:
       packages: write
@@ -82,16 +87,17 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+
   upload-registries:
-    needs: [read-config, test]
+    needs: [prepare, test]
+    runs-on: ubuntu-latest
     if: |
       needs.prepare.outputs.upload-matrix != '{"include": []}' &&
       github.event_name != 'pull_request' && 
       github.ref == 'refs/heads/main'
     strategy:
-      matrix: ${{ fromJSON(needs.read-config.outputs.upload-matrix) }}
+      matrix: ${{ fromJSON(needs.prepare.outputs.upload-matrix) }}
       fail-fast: false
-    runs-on: ubuntu-latest
     steps:
       - name: Prepare ECR Session Token
         if: ${{ contains(matrix.registry-auth-method, 'ecr') }}
